# -*- coding: utf-8 -*-
"""basepaper_jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171HPHXi-ifEI7tUfxHylV6Qxk8tEAnt_

---
# ⚙️ SETUP — Install Dependencies
"""

import torch
print(torch.__version__)
print(torch.cuda.is_available())

pip uninstall numpy pandas -y

pip install numpy pandas

!pip install kaggle opencv-python albumentations seaborn tqdm scikit-learn

import os, random, shutil, zipfile, json, time, io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import cv2
from pathlib import Path
from PIL import Image
from tqdm.notebook import tqdm
from collections import defaultdict

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms, models
from torchvision.utils import make_grid
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_curve, auc, accuracy_score
)

# ── Reproducibility ──
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'✅ Device: {DEVICE}')
if torch.cuda.is_available():
    print(f'   GPU : {torch.cuda.get_device_name(0)}')
    print(f'   VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
else:
    print('   ⚠️  No GPU found — go to Runtime → Change runtime type → T4 GPU')

"""---
# 📦 DATA — Download Real Dataset from Kaggle

We use **[140k Real and Fake Faces](https://www.kaggle.com/datasets/xhlulu/140k-real-and-fake-faces)** — the same type of dataset the original MesoNet paper targets.

### How to get your `kaggle.json`:
1. Go to [kaggle.com](https://www.kaggle.com) → Your profile → **Settings**
2. Scroll to **API** section → Click **Create New Token**
3. A `kaggle.json` file downloads automatically
4. Run the cell below — it will prompt you to upload it

> **Dataset size:** ~3 GB compressed. Colab downloads at ~50 MB/s — about 1 minute.
"""

pip install kaggle

from pathlib import Path
import os
import zipfile

DATA_ROOT = Path('./data/real_vs_fake/real-vs-fake')

if not DATA_ROOT.exists():
    print('⬇️ Downloading dataset from Kaggle...')

    os.system('kaggle datasets download -d xhlulu/140k-real-and-fake-faces')

    print('📦 Extracting...')
    with zipfile.ZipFile('140k-real-and-fake-faces.zip', 'r') as zip_ref:
        zip_ref.extractall('./data')

    os.remove('140k-real-and-fake-faces.zip')
    print(f'✅ Dataset ready at {DATA_ROOT}')

else:
    print(f'✅ Dataset already exists at {DATA_ROOT} — skipping download')

# Sanity check
for split in ['train', 'valid', 'test']:
    for label in ['real', 'fake']:
        folder = DATA_ROOT / split / label
        count = len(list(folder.glob('*.jpg'))) if folder.exists() else 0
        print(f'{split}/{label}: {count:,} images')

"""---
# 🎛️ DATASET SIZE CONFIGURATION

The full dataset has ~70k images per class. Choose how much to use:

| Mode | Images per class (train) | Training time (T4) | Purpose |
|---|---|---|---|
| `'quick'` | 2,000 | ~8–12 min | Fast demo, concept check |
| `'medium'` | 10,000 | ~20–30 min | Good accuracy, balanced speed |
| `'full'` | ~70,000 | ~60–90 min | Best accuracy, paper reproduction |
| `'custom'` | Your choice | — | Set `CUSTOM_N` below |

**Recommendation for a presentation today:** Use `'medium'` — enough data for real results, trains in ~25 min.
"""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 👇 CHANGE THIS to control dataset size
DATASET_MODE = 'medium'   # Options: 'quick', 'medium', 'full', 'custom'
CUSTOM_N     = 5000        # Only used when DATASET_MODE = 'custom'
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIZE_MAP = {
    'quick':  {'train': 2000,  'valid': 500,  'test': 500},
    'medium': {'train': 10000, 'valid': 2000, 'test': 2000},
    'full':   {'train': 70000, 'valid': 10000,'test': 10000},
    'custom': {'train': CUSTOM_N, 'valid': max(500, CUSTOM_N // 5), 'test': max(500, CUSTOM_N // 5)},
}

N_PER_CLASS = SIZE_MAP[DATASET_MODE]
BATCH_SIZE  = 32

print(f'✅ Dataset mode: {DATASET_MODE.upper()}')
print(f'   Train : {N_PER_CLASS["train"]:,} per class  →  {N_PER_CLASS["train"]*2:,} total')
print(f'   Valid : {N_PER_CLASS["valid"]:,} per class  →  {N_PER_CLASS["valid"]*2:,} total')
print(f'   Test  : {N_PER_CLASS["test"]:,} per class  →  {N_PER_CLASS["test"]*2:,} total')
print(f'   Batch size: {BATCH_SIZE}')

"""---
# 🔍 DATA EXPLORATION
"""

# Count available images per split
print('📊 Full Dataset Statistics (before subsetting):')
print('-' * 40)
full_stats = {}
for split in ['train', 'valid', 'test']:
    for label in ['real', 'fake']:
        folder = DATA_ROOT / split / label
        count = len(list(folder.glob('*.jpg'))) if folder.exists() else 0
        full_stats[f'{split}/{label}'] = count
        print(f'  {split}/{label:<8}: {count:>7,} images')

# Visualize sample images — real vs fake
fig, axes = plt.subplots(2, 6, figsize=(18, 7))
fig.suptitle('Sample Images from Dataset: Real (top) vs Fake (bottom)', fontsize=14, fontweight='bold')

for row, label in enumerate(['real', 'fake']):
    img_paths = sorted((DATA_ROOT / 'train' / label).glob('*.jpg'))[:6]
    for col, img_path in enumerate(img_paths):
        img = Image.open(img_path).convert('RGB').resize((128, 128))
        axes[row, col].imshow(img)
        axes[row, col].axis('off')
        color = '#27ae60' if label == 'real' else '#e74c3c'
        if col == 0:
            axes[row, col].set_title(f'{'REAL ✓' if label=="real" else 'FAKE ✗'}',
                                      color=color, fontweight='bold', fontsize=11)

plt.tight_layout()
plt.savefig('sample_images.png', dpi=120, bbox_inches='tight')
plt.show()

# Compare pixel statistics — real vs fake have different artifact signatures
print('\n📈 Pixel statistics comparison (first 200 images per class):')
for label in ['real', 'fake']:
    paths = list((DATA_ROOT / 'train' / label).glob('*.jpg'))[:200]
    means = []
    stds = []
    for p in paths:
        arr = np.array(Image.open(p).convert('RGB').resize((64, 64)), dtype=np.float32)
        means.append(arr.mean())
        stds.append(arr.std())
    print(f'  {label:<5}: mean brightness = {np.mean(means):.1f}  |  mean std (texture) = {np.mean(stds):.1f}')

print('\n✅ Data exploration complete')

"""---
# 🗂️ DATASET & DATALOADER
"""

class DeepfakeDataset(Dataset):
    """
    Loads real/fake face images from directory structure:
        root/split/real/*.jpg
        root/split/fake/*.jpg
    Labels: real=0, fake=1

    Args:
        max_per_class: if set, limits images per class (for quick experiments)
    """
    def __init__(self, root, split, transform=None, max_per_class=None):
        self.transform = transform
        self.samples = []

        for label_name, label_idx in [('real', 0), ('fake', 1)]:
            folder = Path(root) / split / label_name
            if not folder.exists():
                raise FileNotFoundError(f'Folder not found: {folder}')

            paths = []
            for ext in ['*.jpg', '*.jpeg', '*.png']:
                paths.extend(folder.glob(ext))

            # Sort for reproducibility, then shuffle with fixed seed
            paths = sorted(paths)
            rng = random.Random(SEED)
            rng.shuffle(paths)

            # Subset if requested
            if max_per_class is not None:
                paths = paths[:max_per_class]

            for fpath in paths:
                self.samples.append((str(fpath), label_idx))

        # Final shuffle
        random.shuffle(self.samples)
        print(f'   [{split}] Loaded {len(self.samples):,} images '
              f'({len(self.samples)//2:,} real + {len(self.samples)//2:,} fake)')

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        img = Image.open(path).convert('RGB')
        if self.transform:
            img = self.transform(img)
        return img, label


# ── Transforms ──
# Paper uses 256×256, normalize to [-1, 1]
BASE_TRANSFORM = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])  # → [-1,1]
])

# Augmented (used for Phase 3 improved model)
AUGMENT_TRANSFORM = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.RandomGrayscale(p=0.05),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])


def get_loaders(augment_train=False, phase3_jpeg=False):
    """Build train/valid/test DataLoaders respecting N_PER_CLASS config."""

    # Phase 3 adds random JPEG compression to the augment pipeline
    if phase3_jpeg:
        train_tf = _make_jpeg_transform()
    elif augment_train:
        train_tf = AUGMENT_TRANSFORM
    else:
        train_tf = BASE_TRANSFORM

    print(f'Building DataLoaders (mode={DATASET_MODE})...')
    train_ds = DeepfakeDataset(DATA_ROOT, 'train', transform=train_tf,
                                max_per_class=N_PER_CLASS['train'])
    valid_ds = DeepfakeDataset(DATA_ROOT, 'valid', transform=BASE_TRANSFORM,
                                max_per_class=N_PER_CLASS['valid'])
    test_ds  = DeepfakeDataset(DATA_ROOT, 'test',  transform=BASE_TRANSFORM,
                                max_per_class=N_PER_CLASS['test'])

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                              num_workers=2, pin_memory=True)
    valid_loader = DataLoader(valid_ds, batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=2, pin_memory=True)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False,
                              num_workers=2, pin_memory=True)
    return train_loader, valid_loader, test_loader


train_loader, valid_loader, test_loader = get_loaders(augment_train=False)
print(f'\n✅ DataLoaders ready')
print(f'   Train batches: {len(train_loader):,}  ({len(train_loader.dataset):,} images)')
print(f'   Valid batches: {len(valid_loader):,}  ({len(valid_loader.dataset):,} images)')
print(f'   Test  batches: {len(test_loader):,}  ({len(test_loader.dataset):,} images)')

"""---
# ═══════════════════════════════════════════
# 🔵 PHASE 1 — BASE MESONET (Paper Implementation)
# ═══════════════════════════════════════════

## Architecture Overview

MesoNet operates at the **mesoscopic** level — between pixel-level noise (destroyed by video compression) and high-level semantics (indistinguishable to the human eye).

The paper introduces two variants:
- **Meso-4**: 4 × `[Conv → BN → ReLU → MaxPool]` → Flatten → Dense
- **MesoInception-4**: First 2 conv blocks replaced by Inception modules (parallel 1×1, 3×3, 5×5 convolutions)

```
Input (3×256×256)
  └─ Block 1: Conv(3→8, k=3)  + BN + ReLU + MaxPool/2  → (8×128×128)
  └─ Block 2: Conv(8→8, k=5)  + BN + ReLU + MaxPool/2  → (8×64×64)
  └─ Block 3: Conv(8→16, k=5) + BN + ReLU + MaxPool/2  → (16×32×32)
  └─ Block 4: Conv(16→16,k=5) + BN + ReLU + MaxPool/4  → (16×8×8)
  └─ Flatten → Dropout(0.5) → FC(1024→16) → LeakyReLU → Dropout(0.5) → FC(16→1)
```
"""

# ──────────────────────────────────────────────────────────────────
# MESO-4  (Section 3.1 of paper)
# ──────────────────────────────────────────────────────────────────
class Meso4(nn.Module):
    """
    Faithful implementation of Meso-4 from Afchar et al. (2018).
    Input : (B, 3, 256, 256)
    Output: (B, 1) — raw logit; apply sigmoid for fake probability
    """
    def __init__(self, num_classes=1):
        super().__init__()
        # Block 1: 3 → 8 channels, 256 → 128
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 8, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(8),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2)
        )
        # Block 2: 8 → 8 channels, 128 → 64
        self.conv2 = nn.Sequential(
            nn.Conv2d(8, 8, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(8),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2)
        )
        # Block 3: 8 → 16 channels, 64 → 32
        self.conv3 = nn.Sequential(
            nn.Conv2d(8, 16, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2)
        )
        # Block 4: 16 → 16 channels, 32 → 8
        self.conv4 = nn.Sequential(
            nn.Conv2d(16, 16, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(4, 4)
        )
        # Classifier: 16×8×8 = 1024 → 16 → 1
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.5),
            nn.Linear(16 * 8 * 8, 16),
            nn.LeakyReLU(0.1, inplace=True),
            nn.Dropout(0.5),
            nn.Linear(16, num_classes)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        return self.classifier(x)


# ──────────────────────────────────────────────────────────────────
# INCEPTION MODULE  (Section 3.2 of paper)
# Key idea: GAN artifacts appear at MULTIPLE spatial scales.
#   1×1 kernel → pixel-level color inconsistencies
#   3×3 kernel → local texture artifacts
#   5×5 kernel → broader blending seams
#   All concatenated → rich multi-scale forgery representation
# ──────────────────────────────────────────────────────────────────
class InceptionModule(nn.Module):
    def __init__(self, in_channels, out_channels_1, out_channels_3, out_channels_5):
        super().__init__()
        self.branch1 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels_1, kernel_size=1, bias=False),
            nn.BatchNorm2d(out_channels_1), nn.ReLU(inplace=True)
        )
        self.branch2 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels_3, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels_3), nn.ReLU(inplace=True)
        )
        self.branch3 = nn.Sequential(
            nn.Conv2d(in_channels, out_channels_5, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(out_channels_5), nn.ReLU(inplace=True)
        )
        self.out_channels = out_channels_1 + out_channels_3 + out_channels_5

    def forward(self, x):
        return torch.cat([self.branch1(x), self.branch2(x), self.branch3(x)], dim=1)


class MesoInception4(nn.Module):
    """
    MesoInception-4: Meso-4 where conv blocks 1 & 2 are replaced
    by Inception modules (Section 3.2 of paper).
    """
    def __init__(self, num_classes=1):
        super().__init__()
        # Inception Block 1: 3 → 9 channels (1+4+4), 256 → 128
        self.inception1 = nn.Sequential(
            InceptionModule(3, 1, 4, 4),
            nn.MaxPool2d(2, 2)
        )
        # Inception Block 2: 9 → 8 channels (2+4+2), 128 → 64
        self.inception2 = nn.Sequential(
            InceptionModule(9, 2, 4, 2),
            nn.MaxPool2d(2, 2)
        )
        # Standard Conv Blocks 3 & 4 (same as Meso-4)
        self.conv3 = nn.Sequential(
            nn.Conv2d(8, 16, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(16), nn.ReLU(inplace=True), nn.MaxPool2d(2, 2)
        )
        self.conv4 = nn.Sequential(
            nn.Conv2d(16, 16, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(16), nn.ReLU(inplace=True), nn.MaxPool2d(4, 4)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(0.5),
            nn.Linear(16 * 8 * 8, 16),
            nn.LeakyReLU(0.1, inplace=True),
            nn.Dropout(0.5),
            nn.Linear(16, num_classes)
        )

    def forward(self, x):
        x = self.inception1(x)
        x = self.inception2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        return self.classifier(x)


# ── Verify architectures ──
dummy = torch.randn(2, 3, 256, 256)
m4    = Meso4()
mi4   = MesoInception4()

def count_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print('✅ Architecture verification:')
print(f'   Meso-4          output: {m4(dummy).shape}   params: {count_params(m4):,}')
print(f'   MesoInception-4 output: {mi4(dummy).shape}   params: {count_params(mi4):,}')

# ──────────────────────────────────────────────────────────────────
# TRAINING UTILITIES
# ──────────────────────────────────────────────────────────────────
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for imgs, labels in loader:
        imgs   = imgs.to(device)
        labels = labels.float().unsqueeze(1).to(device)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * imgs.size(0)
        preds = (torch.sigmoid(outputs) > 0.5).float()
        correct += (preds == labels).sum().item()
        total   += imgs.size(0)
    return total_loss / total, correct / total


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_preds, all_labels, all_probs = [], [], []
    for imgs, labels in loader:
        imgs       = imgs.to(device)
        labels_dev = labels.float().unsqueeze(1).to(device)
        outputs    = model(imgs)
        loss       = criterion(outputs, labels_dev)
        probs      = torch.sigmoid(outputs)
        preds      = (probs > 0.5).float()
        total_loss += loss.item() * imgs.size(0)
        correct    += (preds == labels_dev).sum().item()
        total      += imgs.size(0)
        all_preds.extend(preds.cpu().numpy().flatten())
        all_labels.extend(labels.numpy())
        all_probs.extend(probs.cpu().numpy().flatten())
    return (total_loss / total, correct / total,
            np.array(all_preds), np.array(all_labels), np.array(all_probs))


def train_model(model, train_loader, valid_loader, epochs=15,
                lr=0.001, model_name='model', criterion=None):
    model      = model.to(DEVICE)
    criterion  = criterion or nn.BCEWithLogitsLoss()
    optimizer  = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler  = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    history      = defaultdict(list)
    best_val_acc = 0
    eval_crit    = nn.BCEWithLogitsLoss()  # always eval with plain BCE for fair comparison

    print(f'\n🚀 Training {model_name} for {epochs} epochs  '
          f'(lr={lr}, device={DEVICE})')
    print(f"   {'Ep':<5} {'TrLoss':<10} {'TrAcc':<10} {'VaLoss':<10} {'VaAcc'}")
    print('   ' + '─' * 48)

    for epoch in range(1, epochs + 1):
        t0 = time.time()
        tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion, DEVICE)
        va_loss, va_acc, _, _, _ = evaluate(model, valid_loader, eval_crit, DEVICE)
        scheduler.step()
        elapsed = time.time() - t0

        history['train_loss'].append(tr_loss)
        history['train_acc'].append(tr_acc)
        history['val_loss'].append(va_loss)
        history['val_acc'].append(va_acc)

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            torch.save(model.state_dict(), f'best_{model_name}.pth')
            marker = '⭐'
        else:
            marker = ''

        print(f'   {epoch:<5} {tr_loss:<10.4f} {tr_acc:<10.4f} '
              f'{va_loss:<10.4f} {va_acc:.4f} {marker}  [{elapsed:.0f}s]')

    print(f'\n   ✅ Best validation accuracy: {best_val_acc:.4f}')
    model.load_state_dict(torch.load(f'best_{model_name}.pth'))
    return model, dict(history)


print('✅ Training utilities ready')

# ── TRAIN: Meso-4 ──
meso4_model, meso4_history = train_model(
    Meso4(), train_loader, valid_loader,
    epochs=15, lr=0.001, model_name='meso4'
)

# ── TRAIN: MesoInception-4 ──
mesoinc_model, mesoinc_history = train_model(
    MesoInception4(), train_loader, valid_loader,
    epochs=15, lr=0.001, model_name='mesoinception4'
)

# ── PHASE 1 RESULTS: Training curves + test evaluation ──
def plot_history(histories, names, title='Training Curves'):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    colors = ['#3498db', '#e74c3c', '#2ecc71']
    for h, name, c in zip(histories, names, colors):
        ep = range(1, len(h['train_acc']) + 1)
        axes[0].plot(ep, h['train_loss'], '--', color=c, alpha=0.5, label=f'{name} train')
        axes[0].plot(ep, h['val_loss'],   '-',  color=c, lw=2,     label=f'{name} val')
        axes[1].plot(ep, h['train_acc'],  '--', color=c, alpha=0.5, label=f'{name} train')
        axes[1].plot(ep, h['val_acc'],    '-',  color=c, lw=2,     label=f'{name} val')
    for ax, ylabel, t in zip(axes, ['Loss', 'Accuracy'], ['Loss Curves', 'Accuracy Curves']):
        ax.set_title(t, fontweight='bold')
        ax.set_xlabel('Epoch')
        ax.set_ylabel(ylabel)
        ax.legend(fontsize=8)
        ax.grid(alpha=0.3)
    axes[1].set_ylim([0.4, 1.0])
    plt.suptitle(title, fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'{title.lower().replace(" ","_")}.png', dpi=120, bbox_inches='tight')
    plt.show()

plot_history([meso4_history, mesoinc_history],
             ['Meso-4', 'MesoInception-4'],
             title='Phase 1 Training Curves')

# ── Full test set evaluation ──
criterion = nn.BCEWithLogitsLoss()
results = {}
for name, model in [('Meso-4', meso4_model), ('MesoInception-4', mesoinc_model)]:
    _, acc, preds, labels, probs = evaluate(model, test_loader, criterion, DEVICE)
    results[name] = {'acc': acc, 'preds': preds, 'labels': labels, 'probs': probs}
    print(f'\n📊 {name} — Test Set Results')
    print('─' * 50)
    print(f'   Accuracy : {acc:.4f} ({acc*100:.1f}%)')
    fpr, tpr, _ = roc_curve(labels, probs)
    print(f'   AUC      : {auc(fpr,tpr):.4f}')
    print(classification_report(labels, preds, target_names=['Real', 'Fake'], digits=4))

# ── Confusion matrices & ROC curves ──
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Phase 1: Confusion Matrices & ROC Curves', fontsize=14, fontweight='bold')

for col, (name, r) in enumerate(results.items()):
    # Confusion matrix
    cm = confusion_matrix(r['labels'], r['preds'])
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0, col],
                xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'],
                annot_kws={'size': 14})
    axes[0, col].set_title(f'{name} — Confusion Matrix', fontweight='bold')
    axes[0, col].set_ylabel('True Label')
    axes[0, col].set_xlabel('Predicted Label')

    # ROC curve
    fpr, tpr, _ = roc_curve(r['labels'], r['probs'])
    roc_auc = auc(fpr, tpr)
    axes[1, col].plot(fpr, tpr, lw=2, color='#3498db', label=f'AUC = {roc_auc:.3f}')
    axes[1, col].plot([0,1],[0,1],'k--', alpha=0.4)
    axes[1, col].fill_between(fpr, tpr, alpha=0.1, color='#3498db')
    axes[1, col].set_xlim([0,1]); axes[1, col].set_ylim([0,1.02])
    axes[1, col].set_title(f'{name} — ROC Curve', fontweight='bold')
    axes[1, col].set_xlabel('False Positive Rate')
    axes[1, col].set_ylabel('True Positive Rate')
    axes[1, col].legend(loc='lower right')
    axes[1, col].grid(alpha=0.3)

plt.tight_layout()
plt.savefig('phase1_evaluation.png', dpi=120, bbox_inches='tight')
plt.show()

print('\n🎯 Phase 1 Complete!')
print(f'   Meso-4 accuracy         : {results["Meso-4"]["acc"]*100:.1f}%')
print(f'   MesoInception-4 accuracy: {results["MesoInception-4"]["acc"]*100:.1f}%')

"""---
# ═══════════════════════════════════════════
# 🔴 PHASE 2 — WEAKNESS ANALYSIS
# ═══════════════════════════════════════════

We **deliberately stress-test** MesoNet to expose its failure modes.

| Test | What we probe | Why it matters |
|---|---|---|
| **W1** | JPEG compression | Real videos are always compressed — artifacts get destroyed |
| **W2** | Image perturbations | Brightness/noise shifts expose distribution brittleness |
| **W3** | Grad-CAM attention | Is the model looking at faces or just background? |
| **W4** | Confidence calibration | Does high confidence actually mean high accuracy? |
"""

# ── WEAKNESS 1: JPEG Compression Robustness ──
# Video compression destroys high-frequency GAN artifacts.
# quality=95 ≈ lossless | quality=30 = heavy compression (typical social media)

def apply_jpeg_compression(tensor_img, quality):
    """Apply JPEG compression to a single normalized tensor image."""
    img = tensor_img.clone().cpu()
    img = (img * 0.5 + 0.5).clamp(0, 1)  # [-1,1] → [0,1]
    img_pil = transforms.ToPILImage()(img)
    buf = io.BytesIO()
    img_pil.save(buf, format='JPEG', quality=quality)
    buf.seek(0)
    return transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.5]*3, [0.5]*3)
    ])(Image.open(buf).convert('RGB'))


@torch.no_grad()
def eval_with_compression(model, loader, quality):
    model.eval()
    correct, total = 0, 0
    for imgs, labels in loader:
        compressed = torch.stack(
            [apply_jpeg_compression(img, quality) for img in imgs]
        ).to(DEVICE)
        labels_dev = labels.float().unsqueeze(1).to(DEVICE)
        preds = (torch.sigmoid(model(compressed)) > 0.5).float()
        correct += (preds == labels_dev).sum().item()
        total   += imgs.size(0)
    return correct / total


quality_levels = [95, 75, 50, 30, 15]
compression_results = {'quality': quality_levels, 'meso4': [], 'mesoinc': []}

print('📉 WEAKNESS 1: JPEG Compression Robustness')
print('─' * 52)
print(f"  {'Quality':<10} {'Meso-4':>12} {'MesoInc-4':>12}")
print('  ' + '─' * 38)

for q in quality_levels:
    acc_m4 = eval_with_compression(meso4_model,  test_loader, q)
    acc_mi = eval_with_compression(mesoinc_model, test_loader, q)
    compression_results['meso4'].append(acc_m4)
    compression_results['mesoinc'].append(acc_mi)
    print(f"  JPEG q={q:<5} {acc_m4:>11.4f} {acc_mi:>12.4f}")

# Plot
plt.figure(figsize=(9, 5))
plt.plot(quality_levels, compression_results['meso4'],
         'o-', label='Meso-4', color='#3498db', lw=2, ms=8)
plt.plot(quality_levels, compression_results['mesoinc'],
         's-', label='MesoInception-4', color='#e74c3c', lw=2, ms=8)
plt.axhline(0.5, color='gray', linestyle='--', alpha=0.5, label='Chance baseline')
plt.axvspan(15, 45, alpha=0.07, color='red', label='Heavy compression zone')
plt.xlabel('JPEG Quality  ←  increasing compression')
plt.ylabel('Accuracy')
plt.title('Weakness 1: JPEG Compression Robustness', fontweight='bold')
plt.legend(); plt.ylim([0.4, 1.0]); plt.grid(alpha=0.3)
plt.gca().invert_xaxis()
plt.tight_layout()
plt.savefig('weakness1_compression.png', dpi=120, bbox_inches='tight')
plt.show()

drop_m4 = compression_results['meso4'][0] - compression_results['meso4'][-1]
print(f'\n⚠️  Meso-4 accuracy drops {drop_m4*100:.1f}pp from quality=95 to quality=15')
print('   Root cause: mesoscopic high-frequency artifacts are destroyed by JPEG DCT.')

# ── WEAKNESS 2: Image Perturbation Robustness ──
# Minor post-processing that doesn't fool humans easily fools MesoNet.

@torch.no_grad()
def eval_with_perturbation(model, loader, perturbation_fn):
    model.eval()
    correct, total = 0, 0
    for imgs, labels in loader:
        perturbed  = perturbation_fn(imgs).to(DEVICE)
        labels_dev = labels.float().unsqueeze(1).to(DEVICE)
        preds = (torch.sigmoid(model(perturbed)) > 0.5).float()
        correct += (preds == labels_dev).sum().item()
        total   += imgs.size(0)
    return correct / total


perturbations = [
    ('No perturbation',     lambda x: x),
    ('Brightness +0.3',     lambda x: (x + 0.3).clamp(-1, 1)),
    ('Brightness -0.3',     lambda x: (x - 0.3).clamp(-1, 1)),
    ('Gaussian noise σ=0.05', lambda x: (x + 0.05 * torch.randn_like(x)).clamp(-1, 1)),
    ('Salt & pepper 1%',    lambda x: _salt_pepper(x, prob=0.01)),
    ('Contrast ×1.5',       lambda x: (x * 1.5).clamp(-1, 1)),
]

def _salt_pepper(imgs, prob=0.01):
    out  = imgs.clone()
    mask = torch.rand_like(imgs) < prob
    vals = torch.where(torch.rand_like(out) > 0.5,
                       torch.ones_like(out), -torch.ones_like(out))
    out[mask] = vals[mask]
    return out

print('📉 WEAKNESS 2: Perturbation Robustness')
print('─' * 58)
print(f"  {'Perturbation':<26} {'Meso-4':>10} {'MesoInc-4':>12} {'Δ Meso-4':>10}")
print('  ' + '─' * 55)

pert_names, pert_m4, pert_mi = [], [], []
baseline_acc = results['Meso-4']['acc']
for name, fn in perturbations:
    acc_m4 = eval_with_perturbation(meso4_model,  test_loader, fn)
    acc_mi = eval_with_perturbation(mesoinc_model, test_loader, fn)
    delta  = acc_m4 - baseline_acc
    pert_names.append(name); pert_m4.append(acc_m4); pert_mi.append(acc_mi)
    print(f"  {name:<26} {acc_m4:>10.4f} {acc_mi:>12.4f} {delta:>+10.4f}")

# Bar chart
x = np.arange(len(pert_names))
w = 0.35
fig, ax = plt.subplots(figsize=(12, 5))
ax.bar(x - w/2, pert_m4,  w, label='Meso-4',         color='#3498db', alpha=0.85)
ax.bar(x + w/2, pert_mi, w, label='MesoInception-4', color='#e74c3c', alpha=0.85)
ax.axhline(0.5, color='gray', linestyle='--', alpha=0.5)
ax.axhline(baseline_acc, color='#3498db', linestyle=':', alpha=0.8, label='Meso-4 clean baseline')
ax.set_xticks(x); ax.set_xticklabels(pert_names, rotation=20, ha='right')
ax.set_ylabel('Accuracy'); ax.set_ylim([0.4, 1.0])
ax.set_title('Weakness 2: Perturbation Robustness', fontweight='bold')
ax.legend(); ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('weakness2_perturbation.png', dpi=120, bbox_inches='tight')
plt.show()
print('\n⚠️  Key finding: MesoNet is brittle to distribution shifts it was never trained on.')

# ── WEAKNESS 3: Grad-CAM Visualization ──
# What spatial regions drive MesoNet's predictions?
# Good model: focuses on facial artifact regions (eyes, chin, blending boundary)
# Bad model:  focuses on background, hair, image borders → shortcut learning

def compute_gradcam(model, img_tensor, target_layer):
    """Manual Grad-CAM (no external library needed)."""
    model.eval()
    activations, gradients = [], []

    h1 = target_layer.register_forward_hook(
        lambda m, i, o: activations.append(o.detach()))
    h2 = target_layer.register_full_backward_hook(
        lambda m, gi, go: gradients.append(go[0].detach()))

    img = img_tensor.unsqueeze(0).to(DEVICE)
    out = model(img)
    model.zero_grad()
    out.backward()
    h1.remove(); h2.remove()

    grads   = gradients[0].squeeze(0)    # (C, H, W)
    acts    = activations[0].squeeze(0)  # (C, H, W)
    weights = grads.mean(dim=(1, 2))     # (C,)
    cam = F.relu((weights[:, None, None] * acts).sum(0))
    cam = cam - cam.min()
    cam = (cam / (cam.max() + 1e-8)).cpu().numpy()
    return cv2.resize(cam, (256, 256))


def denorm(t):
    return (t.cpu() * 0.5 + 0.5).clamp(0,1).permute(1,2,0).numpy()


test_imgs, test_lbls = next(iter(test_loader))
real_idxs = [i for i,l in enumerate(test_lbls.numpy()) if l==0][:3]
fake_idxs = [i for i,l in enumerate(test_lbls.numpy()) if l==1][:3]
target_layer = meso4_model.conv4[0]  # Last conv before classifier

fig, axes = plt.subplots(2, 6, figsize=(20, 7))
fig.suptitle('Weakness 3: Grad-CAM — What is Meso-4 attending to?',
             fontsize=13, fontweight='bold')

for row, (label_name, idxs) in enumerate([('REAL', real_idxs), ('FAKE', fake_idxs)]):
    for j, idx in enumerate(idxs):
        img_t  = test_imgs[idx]
        img_np = denorm(img_t)
        cam    = compute_gradcam(meso4_model, img_t, target_layer)
        heat   = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
        heat   = cv2.cvtColor(heat, cv2.COLOR_BGR2RGB) / 255.0
        overlay = np.clip(0.55 * img_np + 0.45 * heat, 0, 1)

        c = '#27ae60' if label_name == 'REAL' else '#e74c3c'
        axes[row, j*2].imshow(img_np)
        axes[row, j*2].axis('off')
        axes[row, j*2].set_title(f'{label_name}\nOriginal', color=c, fontsize=9, fontweight='bold')
        axes[row, j*2+1].imshow(overlay)
        axes[row, j*2+1].axis('off')
        axes[row, j*2+1].set_title('Grad-CAM\nAttention', fontsize=9)

plt.tight_layout()
plt.savefig('weakness3_gradcam.png', dpi=120, bbox_inches='tight')
plt.show()

print('\n⚠️  Interpretation guide:')
print('   Red/yellow regions = high attention   |   Blue = low attention')
print('   ✓ Good: concentrated on inner face (eyes, nose, jaw boundary)')
print('   ✗ Bad : attention on hair, background, or image borders → shortcut learning')

# ── WEAKNESS 4: Confidence Calibration ──
# A well-calibrated model: when it says 90% confident, it's right 90% of the time.
# MesoNet tends to be overconfident, especially on misclassified examples.

_, _, preds_m4, labels_test, probs_m4 = evaluate(meso4_model, test_loader, criterion, DEVICE)

correct_mask   = (preds_m4 == labels_test)
incorrect_mask = ~correct_mask
confidence     = np.abs(probs_m4 - 0.5) * 2  # 0=uncertain, 1=fully confident

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Weakness 4: Confidence Calibration Analysis', fontsize=13, fontweight='bold')

# Confidence histogram
axes[0].hist(confidence[correct_mask],   bins=30, alpha=0.7, color='#27ae60',
             label=f'Correct   (n={correct_mask.sum()})',   density=True)
axes[0].hist(confidence[incorrect_mask], bins=30, alpha=0.7, color='#e74c3c',
             label=f'Incorrect (n={incorrect_mask.sum()})', density=True)
axes[0].set_xlabel('Prediction Confidence')
axes[0].set_ylabel('Density')
axes[0].set_title('Confidence on Correct vs Incorrect Predictions')
axes[0].legend(); axes[0].grid(alpha=0.3)

# Reliability diagram
n_bins    = 10
bin_edges = np.linspace(0, 1, n_bins + 1)
bin_accs, bin_confs, bin_counts = [], [], []
for i in range(n_bins):
    mask = (probs_m4 >= bin_edges[i]) & (probs_m4 < bin_edges[i+1])
    if mask.sum() > 0:
        bin_accs.append(labels_test[mask].mean())
        bin_confs.append(probs_m4[mask].mean())
        bin_counts.append(mask.sum())
bin_accs  = np.array(bin_accs)
bin_confs = np.array(bin_confs)

axes[1].plot([0,1],[0,1],'k--', label='Perfect calibration', lw=2)
axes[1].plot(bin_confs, bin_accs, 'o-', color='#3498db', lw=2, ms=8, label='Meso-4')
axes[1].fill_between(bin_confs, bin_confs, bin_accs, alpha=0.2, color='#e74c3c',
                     label='Calibration gap')
axes[1].set_xlabel('Mean Predicted Probability')
axes[1].set_ylabel('Fraction of Positives (true accuracy)')
axes[1].set_title('Reliability Diagram (Calibration Curve)')
axes[1].legend(); axes[1].grid(alpha=0.3)
axes[1].set_xlim([0,1]); axes[1].set_ylim([0,1])

plt.tight_layout()
plt.savefig('weakness4_calibration.png', dpi=120, bbox_inches='tight')
plt.show()

ece = np.sum(np.abs(bin_accs - bin_confs) * np.array(bin_counts)) / len(probs_m4)
print(f'\n⚠️  Expected Calibration Error (ECE): {ece:.4f}')
print('   ECE < 0.05 = well calibrated | ECE > 0.10 = poorly calibrated')

print('\n' + '═'*62)
print('🔴 PHASE 2 COMPLETE — Weaknesses Identified:')
print('═'*62)
print('  1. JPEG compression: accuracy collapses under quality < 50')
print('  2. Perturbation brittleness: even minor shifts hurt accuracy')
print('  3. Spatial attention: may focus on wrong regions (shortcut learning)')
print('  4. Miscalibration: overconfident on incorrect predictions')
print('\n  These 4 weaknesses directly motivate every design choice in Phase 3.')

"""---
# ═══════════════════════════════════════════
# 🟢 PHASE 3 — MesoNet++ (Improved Model)
# ═══════════════════════════════════════════

Each improvement directly addresses a weakness found in Phase 2:

| Phase 2 Weakness | MesoNet++ Fix | Technique |
|---|---|---|
| JPEG compression fragility | Train on compressed images | `RandomJPEGCompression` augmentation |
| Perturbation brittleness | Broader training distribution | `ColorJitter`, noise, rotation |
| Wrong spatial attention | Channel re-weighting | **Squeeze-and-Excitation (SE) blocks** |
| Poor calibration | Soft targets | **Label Smoothing** (α=0.1) |
| Limited capacity | Wider feature maps | Conv4: 16→32 channels |
| Unstable late training | Better LR schedule | **OneCycleLR** + gradient clipping |
"""

# ──────────────────────────────────────────────────────────────────
# BUILDING BLOCK 1: Squeeze-and-Excitation Block
# Reference: Hu et al. (2018) "Squeeze-and-Excitation Networks" CVPR
#
# Why it helps: Standard conv layers treat all channels equally.
# SE learns to AMPLIFY channels encoding forgery artifacts and
# SUPPRESS channels encoding irrelevant background statistics.
#
# Mechanism:
#   Squeeze  : Global avg pool (H×W×C) → (1×1×C) — one number per channel
#   Excite   : FC → ReLU → FC → Sigmoid → (1×1×C) weights
#   Recalibrate: multiply input channels by learned weights
# ──────────────────────────────────────────────────────────────────
class SEBlock(nn.Module):
    def __init__(self, channels, reduction=4):
        super().__init__()
        self.se = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(channels, max(1, channels // reduction), bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(max(1, channels // reduction), channels, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        return x * self.se(x).view(x.size(0), x.size(1), 1, 1)


# ──────────────────────────────────────────────────────────────────
# BUILDING BLOCK 2: Random JPEG Compression Augmentation
# Applied during training so the model learns compression-robust features
# ──────────────────────────────────────────────────────────────────
class RandomJPEGCompression:
    """PIL transform: randomly compress image with JPEG (applied with p=0.5)."""
    def __init__(self, quality_range=(40, 95)):
        self.quality_range = quality_range

    def __call__(self, img):
        if random.random() < 0.5:
            q   = random.randint(*self.quality_range)
            buf = io.BytesIO()
            img.save(buf, format='JPEG', quality=q)
            buf.seek(0)
            img = Image.open(buf).convert('RGB')
        return img


def _make_jpeg_transform():
    return transforms.Compose([
        transforms.Resize((256, 256)),
        RandomJPEGCompression(quality_range=(40, 95)),  # ← fix W1
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(degrees=10),
        transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.1, hue=0.05),  # ← fix W2
        transforms.RandomGrayscale(p=0.05),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
    ])


# ──────────────────────────────────────────────────────────────────
# BUILDING BLOCK 3: Label Smoothing BCE
# Reference: Müller et al. (2019) "When Does Label Smoothing Help?"
# Converts hard targets {0, 1} → soft targets {ε/2, 1-ε/2}
# Effect: prevents model from pushing logits to ±∞, improves calibration
# ──────────────────────────────────────────────────────────────────
class LabelSmoothingBCE(nn.Module):
    def __init__(self, smoothing=0.1):
        super().__init__()
        self.smoothing = smoothing

    def forward(self, logits, targets):
        smooth_t = targets * (1 - self.smoothing) + 0.5 * self.smoothing
        return F.binary_cross_entropy_with_logits(logits, smooth_t)


# ──────────────────────────────────────────────────────────────────
# MesoNet++ ARCHITECTURE
# ──────────────────────────────────────────────────────────────────
class MesoPlusPlus(nn.Module):
    """
    MesoNet++ — systematic improvements over MesoInception-4.

    Structural changes:
    - SE attention block after every encoder stage     (fixes W3: shortcut attention)
    - Wider conv4: 16 → 32 channels                   (increases representational capacity)
    - Deeper classifier: 2048 → 64 → 32 → 1           (vs 1024 → 16 → 1 in original)
    - BatchNorm in dense head                          (stabilizes training)

    Training changes (see train_mesopp):
    - Label smoothing α=0.1                            (fixes W4: miscalibration)
    - RandomJPEGCompression augmentation               (fixes W1: compression brittleness)
    - ColorJitter + rotation augmentation              (fixes W2: perturbation brittleness)
    - OneCycleLR + gradient clipping                   (smoother convergence)
    """
    def __init__(self, num_classes=1):
        super().__init__()

        # Encoder
        self.inception1 = nn.Sequential(InceptionModule(3, 1, 4, 4), nn.MaxPool2d(2, 2))  # 9ch, 128
        self.se1         = SEBlock(9)

        self.inception2 = nn.Sequential(InceptionModule(9, 2, 4, 2), nn.MaxPool2d(2, 2))  # 8ch, 64
        self.se2         = SEBlock(8)

        self.conv3 = nn.Sequential(
            nn.Conv2d(8, 16, kernel_size=5, padding=2, bias=False),
            nn.BatchNorm2d(16), nn.ReLU(inplace=True), nn.MaxPool2d(2, 2)                  # 16ch, 32
        )
        self.se3 = SEBlock(16)

        self.conv4 = nn.Sequential(
            nn.Conv2d(16, 32, kernel_size=5, padding=2, bias=False),                        # 16→32!
            nn.BatchNorm2d(32), nn.ReLU(inplace=True), nn.MaxPool2d(4, 4)                  # 32ch, 8
        )
        self.se4 = SEBlock(32)

        # Classifier: 32×8×8=2048 → 64 → 32 → 1
        self.flatten = nn.Flatten()
        self.fc1     = nn.Linear(32 * 8 * 8, 64)
        self.bn1     = nn.BatchNorm1d(64)
        self.act1    = nn.LeakyReLU(0.1, inplace=True)
        self.drop1   = nn.Dropout(0.5)

        self.fc2     = nn.Linear(64, 32)
        self.bn2     = nn.BatchNorm1d(32)
        self.act2    = nn.LeakyReLU(0.1, inplace=True)
        self.drop2   = nn.Dropout(0.3)

        self.fc_out  = nn.Linear(32, num_classes)

    def forward(self, x):
        x = self.se1(self.inception1(x))
        x = self.se2(self.inception2(x))
        x = self.se3(self.conv3(x))
        x = self.se4(self.conv4(x))
        x = self.flatten(x)
        x = self.drop1(self.act1(self.bn1(self.fc1(x))))
        x = self.drop2(self.act2(self.bn2(self.fc2(x))))
        return self.fc_out(x)


# Verify
mpp_test = MesoPlusPlus()
dummy    = torch.randn(2, 3, 256, 256)
print('✅ MesoNet++ architecture verified')
print(f'   Output shape   : {mpp_test(dummy).shape}  (expect [2,1])')
print(f'   Parameters     : {count_params(mpp_test):,}')
print(f'   vs MesoInc-4   : {count_params(MesoInception4()):,}')
print(f'   Param increase : +{count_params(mpp_test)-count_params(MesoInception4()):,} '
      f'(+{(count_params(mpp_test)/count_params(MesoInception4())-1)*100:.0f}%)')

# ── TRAIN MesoNet++ with improved training loop ──

def train_mesopp(model, train_loader, valid_loader, epochs=20,
                 lr=0.001, model_name='mesopp'):
    """MesoNet++ training: label smoothing + OneCycleLR + early stopping."""
    model       = model.to(DEVICE)
    criterion   = LabelSmoothingBCE(smoothing=0.1)   # ← fix W4
    eval_crit   = nn.BCEWithLogitsLoss()              # plain BCE for eval
    optimizer   = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler   = optim.lr_scheduler.OneCycleLR(
        optimizer, max_lr=lr * 3,
        steps_per_epoch=len(train_loader), epochs=epochs,
        pct_start=0.1, anneal_strategy='cos'
    )

    history      = defaultdict(list)
    best_val_acc = 0
    patience_ctr = 0
    PATIENCE     = 6

    print(f'\n🚀 Training {model_name} for up to {epochs} epochs  '
          f'(early stop patience={PATIENCE})')
    print(f"   {'Ep':<5} {'TrLoss':<10} {'TrAcc':<10} {'VaLoss':<10} {'VaAcc'}")
    print('   ' + '─' * 48)

    for epoch in range(1, epochs + 1):
        t0 = time.time()
        model.train()
        total_loss, correct, total = 0, 0, 0
        for imgs, labels in train_loader:
            imgs      = imgs.to(DEVICE)
            labels_t  = labels.float().unsqueeze(1).to(DEVICE)
            optimizer.zero_grad()
            out  = model(imgs)
            loss = criterion(out, labels_t)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()
            total_loss += loss.item() * imgs.size(0)
            preds = (torch.sigmoid(out) > 0.5).float()
            correct += (preds == labels_t).sum().item()
            total   += imgs.size(0)

        tr_loss, tr_acc = total_loss / total, correct / total
        va_loss, va_acc, _, _, _ = evaluate(model, valid_loader, eval_crit, DEVICE)

        history['train_loss'].append(tr_loss)
        history['train_acc'].append(tr_acc)
        history['val_loss'].append(va_loss)
        history['val_acc'].append(va_acc)

        if va_acc > best_val_acc:
            best_val_acc = va_acc
            torch.save(model.state_dict(), f'best_{model_name}.pth')
            marker = '⭐'
            patience_ctr = 0
        else:
            marker = ''
            patience_ctr += 1

        elapsed = time.time() - t0
        print(f'   {epoch:<5} {tr_loss:<10.4f} {tr_acc:<10.4f} '
              f'{va_loss:<10.4f} {va_acc:.4f} {marker}  [{elapsed:.0f}s]')

        if patience_ctr >= PATIENCE:
            print(f'   ⏹  Early stop at epoch {epoch} (no improvement for {PATIENCE} epochs)')
            break

    print(f'\n   ✅ Best val accuracy: {best_val_acc:.4f}')
    model.load_state_dict(torch.load(f'best_{model_name}.pth'))
    return model, dict(history)


# Build JPEG-augmented loaders
train_loader_p3, valid_loader_p3, test_loader_p3 = get_loaders(phase3_jpeg=True)
print('\n✅ Phase 3 DataLoaders ready (with JPEG + strong augmentation)')

# Train
mesopp_model, mesopp_history = train_mesopp(
    MesoPlusPlus(), train_loader_p3, valid_loader_p3,
    epochs=20, lr=0.001, model_name='mesopp'
)

# ── PHASE 3 EVALUATION: Full head-to-head comparison ──
eval_crit = nn.BCEWithLogitsLoss()

# Clean test set evaluation for all three models
_, acc_m4,  preds_m4,  labels_t, probs_m4  = evaluate(meso4_model,   test_loader, eval_crit, DEVICE)
_, acc_mi,  preds_mi,  _,        probs_mi  = evaluate(mesoinc_model,  test_loader, eval_crit, DEVICE)
_, acc_mpp, preds_mpp, _,        probs_mpp = evaluate(mesopp_model,   test_loader, eval_crit, DEVICE)

print('📊 CLEAN TEST SET — All Three Models')
print('─' * 55)
print(f"  {'Model':<22} {'Accuracy':>10} {'AUC':>8}")
print('  ' + '─' * 42)
for name, acc, probs in [('Meso-4', acc_m4, probs_m4),
                          ('MesoInception-4', acc_mi, probs_mi),
                          ('MesoNet++', acc_mpp, probs_mpp)]:
    fpr, tpr, _ = roc_curve(labels_t, probs)
    print(f"  {name:<22} {acc*100:>9.2f}%  {auc(fpr,tpr):>7.4f}")

print('\n📊 JPEG q=50 (COMPRESSED) TEST — Robustness Comparison')
print('─' * 55)
print(f"  {'Model':<22} {'Compr Acc':>10} {'Drop':>8}")
print('  ' + '─' * 42)
for name, model, acc_clean in [('Meso-4', meso4_model, acc_m4),
                                 ('MesoInception-4', mesoinc_model, acc_mi),
                                 ('MesoNet++', mesopp_model, acc_mpp)]:
    acc_c = eval_with_compression(model, test_loader, quality=50)
    print(f"  {name:<22} {acc_c*100:>9.2f}%  {(acc_c-acc_clean)*100:>+7.2f}pp")

# ── FINAL COMPARISON PLOTS (4 panels) ──
all_models_data = [
    ('Meso-4',          meso4_model,   meso4_history,   acc_m4,  probs_m4),
    ('MesoInception-4', mesoinc_model, mesoinc_history, acc_mi,  probs_mi),
    ('MesoNet++',       mesopp_model,  mesopp_history,  acc_mpp, probs_mpp),
]
colors = ['#3498db', '#e74c3c', '#2ecc71']

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Phase 3: Final Model Comparison', fontsize=15, fontweight='bold')

# Panel 1: Validation accuracy curves
for (name, model, history, acc, probs), c in zip(all_models_data, colors):
    ep = range(1, len(history['val_acc']) + 1)
    axes[0,0].plot(ep, history['val_acc'], '-', color=c, lw=2, label=name)
axes[0,0].set_title('Validation Accuracy During Training')
axes[0,0].set_xlabel('Epoch'); axes[0,0].set_ylabel('Accuracy')
axes[0,0].legend(); axes[0,0].grid(alpha=0.3); axes[0,0].set_ylim([0.5, 1.0])

# Panel 2: ROC curves
for (name, model, history, acc, probs), c in zip(all_models_data, colors):
    fpr, tpr, _ = roc_curve(labels_t, probs)
    axes[0,1].plot(fpr, tpr, color=c, lw=2, label=f'{name}  AUC={auc(fpr,tpr):.3f}')
axes[0,1].plot([0,1],[0,1],'k--', alpha=0.4)
axes[0,1].set_title('ROC Curves — All Models')
axes[0,1].set_xlabel('FPR'); axes[0,1].set_ylabel('TPR')
axes[0,1].legend(loc='lower right'); axes[0,1].grid(alpha=0.3)

# Panel 3: JPEG compression robustness comparison
ql = [95, 75, 50, 30, 15]
for (name, model, history, acc, probs), c in zip(all_models_data, colors):
    accs = [eval_with_compression(model, test_loader, q) for q in ql]
    axes[1,0].plot(ql, accs, 'o-', color=c, lw=2, ms=7, label=name)
axes[1,0].axhline(0.5, color='gray', linestyle='--', alpha=0.5)
axes[1,0].set_title('JPEG Compression Robustness')
axes[1,0].set_xlabel('JPEG Quality  (←  increasing compression)')
axes[1,0].set_ylabel('Accuracy')
axes[1,0].legend(); axes[1,0].grid(alpha=0.3)
axes[1,0].set_ylim([0.4, 1.0]); axes[1,0].invert_xaxis()

# Panel 4: Bar chart — clean vs compressed accuracy per model
model_names = ['Meso-4', 'MesoInc-4', 'MesoNet++']
clean_accs  = [acc_m4, acc_mi, acc_mpp]
comp_accs   = [eval_with_compression(m, test_loader, 50)
               for (_, m, _, _, _) in all_models_data]

x  = np.arange(3)
w  = 0.35
b1 = axes[1,1].bar(x - w/2, clean_accs, w, label='Clean',         color='#3498db', alpha=0.9)
b2 = axes[1,1].bar(x + w/2, comp_accs,  w, label='JPEG q=50',     color='#e67e22', alpha=0.9)
axes[1,1].set_xticks(x); axes[1,1].set_xticklabels(model_names)
axes[1,1].set_ylabel('Accuracy'); axes[1,1].set_ylim([0.5, 1.0])
axes[1,1].set_title('Clean vs Compressed Accuracy')
axes[1,1].legend(); axes[1,1].grid(axis='y', alpha=0.3)
for bar in list(b1) + list(b2):
    h = bar.get_height()
    axes[1,1].annotate(f'{h*100:.1f}%',
                       xy=(bar.get_x() + bar.get_width()/2, h),
                       xytext=(0, 3), textcoords='offset points',
                       ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('phase3_final_comparison.png', dpi=120, bbox_inches='tight')
plt.show()

# ── FINAL SUMMARY ──
print('\n' + '═'*68)
print('🏆 FINAL RESULTS SUMMARY')
print('═'*68)
print(f"  {'Model':<22} {'Params':>9} {'Clean Acc':>11} {'JPEG q=50':>11} {'AUC':>8}")
print('  ' + '─'*63)

for (name, model, history, acc_clean, probs), c in zip(all_models_data, colors):
    n_p     = count_params(model)
    acc_c50 = eval_with_compression(model, test_loader, quality=50)
    fpr, tpr, _ = roc_curve(labels_t, probs)
    roc_auc = auc(fpr, tpr)
    print(f'  {name:<22} {n_p:>9,} {acc_clean*100:>10.2f}% {acc_c50*100:>10.2f}%  {roc_auc:>7.4f}')

print('═'*68)
print()
print('📚 KEY LEARNINGS')
print()
print('  PHASE 1 — Understanding the Paper:')
print('  • MesoNet exploits mesoscopic GAN artifacts at intermediate spatial scales')
print('  • Inception modules: parallel 1×1 / 3×3 / 5×5 kernels capture multi-scale forgery cues')
print('  • ~27K parameters — a tiny model that works because deepfake artifacts are structural')
print()
print('  PHASE 2 — What We Broke:')
print('  • JPEG compression destroys the high-frequency artifacts MesoNet relies on')
print('  • Distribution shift (brightness, noise) reveals the model memorized training stats')
print('  • Grad-CAM: model may learn shortcuts from background/hair rather than face artifacts')
print('  • ECE > 0.05 confirms overconfident predictions, especially on misclassified samples')
print()
print('  PHASE 3 — What We Fixed:')
print('  • SE blocks learn channel importance → suppresses shortcut channels')
print('  • JPEG augmentation during training → compression-robust feature learning')
print('  • Label smoothing → reduced overconfidence, better ECE')
print('  • OneCycleLR + AdamW → faster convergence, better generalization')
print()
print('  OPEN RESEARCH DIRECTIONS:')
print('  → Temporal modeling    : LSTM/GRU over consecutive video frames')
print('  → Multi-modal          : cross-modal audio-visual inconsistency detection')
print('  → Cross-dataset gen.   : train on Deepfakes, evaluate on FaceSwap, DFDC')
print('  → Adversarial training : robust against adversarially optimized deepfakes')